/* =====================================================================
                           05_Magnitude_Analysis
===================================================================== */


-- ---------------------------------------------------------------------
-- 1. Find total customers by countries
-- ---------------------------------------------------------------------
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- ---------------------------------------------------------------------
-- 2. Find total customers by gender
-- ---------------------------------------------------------------------
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- ---------------------------------------------------------------------
-- 3. Find total products by category
-- ---------------------------------------------------------------------
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- ---------------------------------------------------------------------
-- 4. What is the average costs in each category?
-- ---------------------------------------------------------------------
SELECT
    category,
    ROUND(AVG(cost), 2) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- ---------------------------------------------------------------------
-- 5. What is the total revenue generated for each category?
-- ---------------------------------------------------------------------
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- ---------------------------------------------------------------------
-- 6. Find total revenue generated by each customer
--    (Returns many rows — one per customer. Sorted top-first.)
-- ---------------------------------------------------------------------
SELECT
    c.customer_key,
    c.customer_number,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.customer_number, c.first_name, c.last_name
ORDER BY total_revenue DESC;


-- ---------------------------------------------------------------------
-- 7. What is the distribution of sold items across countries?
-- ---------------------------------------------------------------------
SELECT
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;
